Задание 1. Система контроля версии
RomanNechaev/Tinkoff_Java pull request #1
Opened 2023-09-17 17:16 UTC by RomanNechaev

2023-09-19 08:50 UTC, EMDavl requested changes
Отличный опыт! Уверен что все цели по окончании курса будут выполнены. Оставил пару комментов, про origin и gitignore нужно поправить, про pull чисто информационное

2023-09-19 08:50 UTC, EMDavl commented on .gitignore
> +!/README.MD
Это необязательно т.к. есть то же самое на 3 строке

2023-09-19 08:50 UTC, EMDavl commented on README.MD
> +  компьютер. Для использования команды нужно указать адрес центрального хранилища, можно ссылаться через слово origin. Пример: git clone https://github.com/RomanNechaev/Tinkoff_Java.git
> можно ссылаться через слово origin

Не очень понял что ты имеешь ввиду. Для клонирования необходимо указать адрес репозитория, через origin склонировать не получится т.к. после git init никакого origin'а пока не определено.

В общем и целом origin это просто дефолтный alias для URL'а репозитория. Этот элиас может быть любым, в зависимости от того как ты его определишь через `git remote add <name> <url>` для добавления или `git clone -o <name> <url>` при клонировании.

2023-09-19 08:50 UTC, EMDavl commented on README.MD
> +* pull - забирает изменения из удаленного репозитория и интегрирует их с изменениями в локальном репозитории. Аналогично двум последовательным командам: git fetch, git merge. Пример использования: gi
Дефолтное поведение - так как ты и описал (`git fetch && git merge`), но можно изменить дефолтное поведение на такое, при котором выполняется не merge, а rebase.

Держу в курсе так сказатб

2023-09-24 13:55 UTC, RomanNechaev commented on README.MD
> +  компьютер. Для использования команды нужно указать адрес центрального хранилища, можно ссылаться через слово origin. Пример: git clone https://github.com/RomanNechaev/Tinkoff_Java.git
исправил

2023-09-25 09:39 UTC, EMDavl commented
В следующий раз на платформе тоже возвращай на проверку плиз, а то я могу не заметить уведомление на почте и пропустить твои правки blessrng

2023-09-26 16:49 UTC, EMDavl approved these changes

2023-10-08 19:30 UTC, merged