Задача 3. Создание Spring приложения
RomanNechaev/Tinkoff_Java pull request #3
Opened 2023-10-01 16:15 UTC by RomanNechaev

2023-10-03 09:45 UTC, EMDavl requested changes

2023-10-03 09:45 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +
Форматирование поехало: лишние пропуски строки

2023-10-03 09:45 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/repositories/impl/WeatherRepositoryImpl.java
> +        weatherList.add(index, weather);
Удаление и добавление можно заменить на `weatherList.set(index, weather)`

2023-10-03 09:45 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/impl/WeatherServiceImpl.java
> +        Weather weather = new Weather(weatherModel.name(), weatherModel.temperatureValue(), weatherModel.date(), weatherModel.time());
Может быть такое, что в модели и в запросе переданы разные имена регионов, нужно обрабатывать этот случай

2023-10-03 09:45 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/impl/WeatherServiceImpl.java
> +                .findByName(weatherModel.name())
Аналогично предыдущему - имя города из запроса и из модели может быть разным

2023-10-06 17:05 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +
исправил

2023-10-06 17:05 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/repositories/impl/WeatherRepositoryImpl.java
> +        weatherList.add(index, weather);
исправил

2023-10-06 17:05 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/impl/WeatherServiceImpl.java
> +        Weather weather = new Weather(weatherModel.name(), weatherModel.temperatureValue(), weatherModel.date(), weatherModel.time());
исправил

2023-10-06 17:05 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/impl/WeatherServiceImpl.java
> +                .findByName(weatherModel.name())
исправил

2023-10-08 17:41 UTC, EMDavl approved these changes

2023-10-08 19:29 UTC, merged