Task3. Клиент для внешнего REST сервиса
RomanNechaev/Tinkoff_Java pull request #5
Opened 2023-10-08 20:01 UTC by RomanNechaev

2023-10-12 12:03 UTC, EMDavl requested changes

2023-10-12 12:03 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/client/WeatherApiClient.java
> +                .onStatus(HttpStatusCode::is4xxClientError, response -> {
500 тоже по хорошему бы обрабатывать и отдавать от твоего сервиса что-то вроде 502 кода

2023-10-12 12:03 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/config/WeatherClientProperties.java
> +public class WeatherClientProperties {
Чтобы проперти активировались надо проставить `@EnableConfigurationProperties` и указать класс пропертей, иначе не будут параметры подтягиваться

2023-10-12 12:03 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/config/WebClientConfiguration.java
> +                .baseUrl(Objects.requireNonNull(environment.getProperty("api.base_url")))
Думаю, что лучше заюзать WeatherClientProperties

2023-10-12 12:03 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +    public WeatherController(WeatherService weatherService, WeatherApiService weatherApiService) {
В целом на ломбоковский @RequiredArgsConstructor заменить можно, чтобы от boilerplate'а избавиться

2023-10-12 12:03 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/crud/CreateOperation.java
> +public interface CreateOperation {
Не оч понял мува, можешь подсказать в чем заключалась идея выделения отдельных операций? Обычно все сразу делают в сервисе, без выделения интерфейса под все операции

2023-10-12 15:16 UTC, EMDavl commented
Было бы круто, если б была ридмишка по тому что и куда добавлять

2023-10-13 18:45 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/client/WeatherApiClient.java
> +                .onStatus(HttpStatusCode::is4xxClientError, response -> {
В данном случае я правильно понимаю, что важно различать ошибки на стороне стороннего сервиса и нашего?
Т.е мы как прокси сервер можем кидать ошибку 502, если получили от стороннего сервиса ошибку 400 с кодом 9999 судя по доке https://www.weatherapi.com/docs/, а вот ошибка 400 с кодом 2008 это ошибка уже нашего сервера, т.к мы работаем с недействительном  ключом, следовательно в таком случае уже выбрасываем 500?

2023-10-13 19:12 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/crud/CreateOperation.java
> +public interface CreateOperation {
Планировал как-то расширить архитектуру и поиграться в ООП, но в итоге сейчас понимаю, что без создания двух сервисов ни как не обойтись.

2023-10-15 08:14 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/client/WeatherApiClient.java
> +                .onStatus(HttpStatusCode::is4xxClientError, response -> {
Да, все так

2023-10-15 08:26 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/crud/CreateOperation.java
> +public interface CreateOperation {
На мой взгляд это надо делать либо более дженеричным, чтобы не писать под каждую сущность и способ создания по отдельному методу, либо, что мне кажется более правильным, уйти от такого подхода и хранить логику взаимодействия с сущностью непосредственно в сервисе, который создан под эту сущность / процесс. 

В текущей реализации, при расширении твоей системы, например, новыми сущностями, тебе потенциально надо будет дописывать здесь логику под эти сущности и либо делать методы дефолтными с пробросом ошибки, либо имплементировать эти методы и в сервисах, которые с этой сущностью вообще никак не связаны. 

В текущей домашке на баллы это не влияет, но может помешать в будущем расширению системы

2023-10-15 11:19 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/client/WeatherApiClient.java
> +                .onStatus(HttpStatusCode::is4xxClientError, response -> {
добавил обработку

2023-10-15 11:20 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/config/WeatherClientProperties.java
> +public class WeatherClientProperties {
Добавил, правда не получилось разобраться, как хранить проперти в файлах, отличных от дефолтного application.propertiesю

2023-10-15 11:20 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/config/WebClientConfiguration.java
> +                .baseUrl(Objects.requireNonNull(environment.getProperty("api.base_url")))
исправил

2023-10-15 11:20 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +    public WeatherController(WeatherService weatherService, WeatherApiService weatherApiService) {
исправил

2023-10-15 11:23 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/crud/CreateOperation.java
> +public interface CreateOperation {
Учел замечания

2023-10-15 13:45 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/config/WeatherClientProperties.java
> +public class WeatherClientProperties {
Можно по профилям (`application-local.properties`, `application-prod.properties`, `application-test.properties`) и выставляя в спринге активный профиль вместо или в дополнение к профилю default будут подтягиваться проперти, но это больше для локальной разработки удобно. 

А для чего и как хотел использовать? В течение недели могу глянуть, отписать

2023-10-23 11:39 UTC, merged