Task5. Бд Часть 2 Практика
RomanNechaev/Tinkoff_Java pull request #7
Opened 2023-10-22 17:55 UTC by RomanNechaev

2023-10-23 16:07 UTC, EMDavl requested changes

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +    public ResponseEntity<WeatherEntity> getWeatherByCityName(@PathVariable String city) {
Надо возвращать DTO вместо Entity

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/resources/db/changelog/changelog.JSON
> +              "clustered":true,
Почему кластеризованные?

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/spring_data_jpa/CrudService.java
> +    @Transactional(isolation = Isolation.REPEATABLE_READ)
Почему такой уровень?

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/repositories/mapper/WeatherEntityMapper.java
> +                    (City) resultSet.getObject(CITY_ID),
Так работать не будет, т.к. тебе из базы возвращается long, а ты кастишь в City

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/jdbc/impl/JdbcWeatherEntityCrudServiceImpl.java
> +        WeatherEntity entity = weatherEntityCrudRepository.save(weatherEntity);
При попытке сохранить метод падает с ошибкой т.к. недостаточно параметров передано в prepared statement. Аналогично для ряда других методов

```
Parameter "#4" is not set; SQL statement:
UPDATE WEATHER
SET TEMPERATURE = ?, CITY_ID = ?, WEATHER_TYPE_ID = ?
WHERE ID = ? [90012-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:646) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.get(DbException.java:223) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.message.DbException.get(DbException.java:199) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.expression.Parameter.checkSet(Parameter.java:75) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Prepared.checkParameters(Prepared.java:207) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.CommandContainer.update(CommandContainer.java:159) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.command.Command.executeUpdate(Command.java:252) ~[h2-2.1.214.jar:2.1.214]
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:254) ~[h2-2.1.214.jar:2.1.214]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.0.1.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.0.1.jar:na]
	at tinkoff.training.repositories.jdbc.impl.WeatherEntityRepositoryImpl.update(WeatherEntityRepositoryImpl.java:36) ~[main/:na]
	... 74 common frames omitted
```

2023-10-23 16:07 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/services/jdbc/impl/JdbcWeatherEntityCrudServiceImpl.java
> +        WeatherEntity entity = weatherEntityCrudRepository.save(weatherEntity);
Спринговая транзакция не работает в рамках JDBC конекшена, поэтому у тебя выходит что транзакция создалась в одном месте, в другом конекшене выполнился запрос и транзакция закрылась. Соотв-но сам запрос выполнился вне этой транзакции

2023-10-23 16:11 UTC, EMDavl requested changes

2023-10-23 16:11 UTC, EMDavl commented on fintech/src/main/java/tinkoff/training/models/WeatherModel.java
> +@Entity
Почему это тоже entity? Есть же WeatherEntity. Еще ща заметил что у тебя в entities лежит класс Weather, почему бы не переиспользовать его и натянуть на БД?

2023-10-23 16:14 UTC, EMDavl commented
Вот это должно помочь в фиксе отображения, сделай плиз
https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch

2023-10-29 16:39 UTC, RomanNechaev commented on fintech/src/main/resources/db/changelog/changelog.JSON
> +              "clustered":true,
хотел повысить производительность, но , сейчас вспомнил, что у меня в таблице есть primary key, который и будет являться кластерным индексом. Думал, что в h2 можно создавать более 1 кластеризованного индекса. Сейчас понимаю, что это невозможно

2023-10-29 16:39 UTC, RomanNechaev commented on fintech/src/main/resources/db/changelog/changelog.JSON
> +              "clustered":true,
убрал со всех индексов кластерный тип

2023-10-29 16:43 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/models/WeatherModel.java
> +@Entity
исправил, но в оставил два почти одинаковых репозитория для Weather, один из 3 дз, другой для 5.

2023-10-29 17:04 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/controllers/WeatherController.java
> +    public ResponseEntity<WeatherEntity> getWeatherByCityName(@PathVariable String city) {
Теперь возвращаю во всех контроллер DTO, только для упрощения задачи, поля у DTO и Entity совпадают, чтобы MapStruct сам мапил)

2023-11-02 12:08 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/spring_data_jpa/CrudService.java
> +    @Transactional(isolation = Isolation.REPEATABLE_READ)
Проанализировав, я пришел к выводу, что стоит ставить следующие уровни изоляции в сервиса:

- **create, update** - SERIALIZABLE, т.к данный уровень защищает от чтения фантомов, которые у нас могут возникнуть(если этого уровня не достигать, то может произойти ситуация, когда две параллельных транзакции увидят, что нет сущности с именем X, и создадут два дубликата) 
- **findById, findAll, deleteById** - READ_COMMITTED - т.к данные уровень защищает от  "грязного чтения", допустим одна транзакция пытается обновить сущность а затем откатывает изменение, а мы в этот промежуток читаем данные, что приводит к несогласованному состоянию. Для delete. соответственно, защищаемся от возможности удаления незакомиченных данных

2023-11-02 12:10 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/repositories/mapper/WeatherEntityMapper.java
> +                    (City) resultSet.getObject(CITY_ID),
исправил, теперь find_weather_query - возвращает таблицу, с названием названием города и названием типа,  чтобы в дальнейшем преобразовать в City и WeatherType

2023-11-02 12:10 UTC, RomanNechaev commented on fintech/src/main/java/tinkoff/training/services/jdbc/impl/JdbcWeatherEntityCrudServiceImpl.java
> +        WeatherEntity entity = weatherEntityCrudRepository.save(weatherEntity);
исправил

2023-11-06 09:47 UTC, merged