Task6. Тестовое покрытие приложений.
RomanNechaev/Tinkoff_Java pull request #9
Opened 2023-10-29 20:55 UTC by RomanNechaev

2023-11-06 11:46 UTC, EMDavl requested changes
В целом все ок, но не нашел тестов на интеграцию с weather api. Поэтому пока -2 балла

2023-11-06 11:46 UTC, EMDavl commented on fintech/src/test/java/tinkoff/training/controllers/spring_data_jpa/WeatherEntityControllerTest.java
> +    void setUp() {
Создаются лишние данные (testWeather2 и т.п.), которые далее в тесте не используются.

2023-11-06 11:46 UTC, EMDavl commented on fintech/src/test/java/unit/services/WeatherCrudServiceTest.java
> +@ContextConfiguration(classes = {WeatherServiceImpl.class})
Потерял пустую строку между импортами и аннотацией

2023-11-11 14:08 UTC, RomanNechaev commented on fintech/src/test/java/tinkoff/training/controllers/spring_data_jpa/WeatherEntityControllerTest.java
> +    void setUp() {
исправил в ветке task7

2023-11-11 14:09 UTC, RomanNechaev commented on fintech/src/test/java/unit/services/WeatherCrudServiceTest.java
> +@ContextConfiguration(classes = {WeatherServiceImpl.class})
исправил в ветке task7

2023-11-11 14:09 UTC, RomanNechaev commented
Добавил тест для WeatherApiService -> https://github.com/RomanNechaev/Tinkoff_Java/commit/92c3a8af93901e0695d6009874458541ef85741a

2023-11-18 15:57 UTC, closed without merging